document.getElementById("white").addEventListener("click",()=>{
    document.body.style.background="white";
    document.body.style.color="black";
});
document.getElementById("aqua").addEventListener("click",()=>{
    document.body.style.background="aqua";
});
document.getElementById("violet").addEventListener("click",()=>{
    document.body.style.background="violet";
});
document.getElementById("black").addEventListener("click",()=>{
    document.body.style.background="black";
    document.body.style.color="white";
});